[package]
name = "gnostr-bins"
version = "0.0.50"
license = "Apache-2.0"
rust-version = "1.79"
edition = "2021"
readme = "README.md"
homepage = "https://github.com/gnostr-org/gnostr-bins"
repository = "https://github.com/gnostr-org/gnostr-bins"
documentation = "https://github.com/gnostr-org/gnostr/bins"
categories = ["version-control", "development-tools", "gnostr", "nostr"]
keywords = ["git", "gnostr", "nostr"]
description = "git+nostr workflow utility"
authors = ["gnostr <admin@gnostr.org>", "Mike Dilger <mike@mikedilger.com>", "DanConwayDev <DanConwayDev@protonmail.com>", "Max Inden <mail@max-inden.de>", "fiatjaf <fiatjaf@gmail.com>", "Nate Levin <natelevincycling@gmail.com>", "Nethanja Focking <nethanja@nethanja.de>", "Daniele Tonon <tonon@vitamino.it>", "jeremyd (@jeremyd)", "Sebastian Thiel <sebastian.thiel@icloud.com>"]

[dependencies]
argparse    = "0.2.2"
ascii = "1.1.0"
base64 = "0.21"
bech32 = "0.9"
chrono = { version = "0.4.34", features = ["serde"] }
futures = { version = "0.3.6", features = ["async-await", "futures-executor"] }
getopts = "0.2.21"
git2 = "^0.18"
hex = "0.4"
http = "0.2"
k256 = { version = "0.13", features = [ "schnorr", "ecdh" ] }
log = "0.4.21"
gnostr-types = { version = "0.7.0-unstable", path = "vendor/nostr-types", features = ["speedy"] }
num-bigint = "0.4.4"
pad = "0.1.6"
rand = { version = "0.7.3", default-features = false, features = ["std"] }
rand_core = "0.6"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls-webpki-roots"] }
rpassword = "7.2"
rust-crypto = "0.2.36"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
sha2 = "0.10.8"
sha256 = "1.2.2"
structopt = "0.3.26"
time = "0.1.42"
tungstenite = { version = "0.18", features = [ "rustls-tls-webpki-roots" ] }
url = { version = "2.5.0", features = ["serde"] }
zeroize = "1.5"

[dev-dependencies]
cargo-dist = "0.21.1"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace]
members = [
    ".",
    "vendor/nostr-types",
    "vendor/nostr-types/vendor/speedy/speedy-derive",
    "vendor/nostr-types/vendor/speedy/static-tests",
]

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.21.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "gnostr-org/homebrew-gnostr-org"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Whether to install an updater program
install-updater = true
