[package]
name = "gnostr-bins"
version = "0.1.0"
edition = "2021"
authors = ["gnostr <admin@gnostr.org>", "Mike Dilger <mike@mikedilger.com>"]
description = "gnostr: a git+nostr workflow utility"
repository = "https://github.com/gnostr-org/gnostr-bins"
documentation = "https://docs.rs/gnostr-bins"
readme = "README.md"
keywords = [ "nostr", "gnostr" ]
license = "MIT"

[dependencies]
base64 = "0.21"
bech32 = "0.9"
hex = "0.4"
http = "0.2"
k256 = { version = "0.13", features = [ "schnorr", "ecdh" ] }
nip44 = { version = "0.1.0", path = "vendor/nip44" }
nostr-types = { version = "0.7.0-unstable", path = "vendor/nostr-types", features = ["speedy"] }
rand = "0.8"
rand_core = "0.6"
reqwest = { version = "0.11", default-features = false, features = [ "blocking", "json", "rustls-tls-webpki-roots"  ] }
rpassword = "7.2"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tungstenite = { version = "0.18", features = [ "rustls-tls-webpki-roots" ] }
zeroize = "1.5"
