[package]
name = "gnostr-bins"
version = "0.0.1"
edition = "2021"
authors = ["Mike Dilger <mike@mikedilger.com>", "gnostr <admin@gnostr.org>"]
description = "Binaries for gnostr"
repository = "https://github.com/gnostr-org/gnostr-bins"
documentation = "https://docs.rs/gnostr-bins"
readme = "README.md"
keywords = [ "nostr", "gnostr", "git"]
license = "MIT"

[source."git+https://github.com/mikedilger/nip44?rev=e38717f86ccccb91c25ebf07881a77d66411161c"]
git = "https://github.com/mikedilger/nip44"
rev = "e38717f86ccccb91c25ebf07881a77d66411161c"
replace-with = "vendored-sources"

[source."git+https://github.com/mikedilger/nostr-types"]
git = "https://github.com/mikedilger/nostr-types"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[dependencies]
base64 = "0.21"
bech32 = "0.9"
hex = "0.4"
http = "0.2"
k256 = { version = "0.13", features = [ "schnorr", "ecdh" ] }
nostr-types = { git = "https://github.com/mikedilger/nostr-types" }
rand = "0.8"
rand_core = "0.6"
reqwest = { version = "0.11", default-features = false, features = [ "blocking", "json", "rustls-tls-webpki-roots"  ] }
rpassword = "7.2"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tungstenite = { version = "0.18", features = [ "rustls-tls-webpki-roots" ] }
zeroize = "1.5"
