[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/mikedilger/nip44?rev=e6ab1bc4480fd53aa854814bbacacf200c51af14"]
git = "https://github.com/mikedilger/nip44"
rev = "e6ab1bc4480fd53aa854814bbacacf200c51af14"
replace-with = "vendored-sources"

[source."git+https://github.com/mikedilger/nostr-types"]
git = "https://github.com/mikedilger/nostr-types"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
